module NouEnOf

import StdEnv

and`    = ... all ...
or`     = ... any ...

all_l p	= foldl ...
all_r p	= foldr ...
any_l p	= foldl ...
any_r p	= foldr ...

Start   = all_l id [False:repeat True ]
Start   = any_l id [True :repeat False]
Start   = all_r id [False:repeat True ]
Start   = any_r id [True :repeat False]
